
server:
  port: 8081  # Change to the desired port for your Spring Boot application

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: 151022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect